import type { Metadata } from "next";
import "./globals.css";
import { ptSansFont } from "./fonts";

export const metadata: Metadata = {
  title: "Flexion Code Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ptSansFont.className}>{children}</body>
    </html>
  );
}
